swagger: '2.0'
info:
  title: cloudinary-ct-dev-run
  version: 1.0.0
schemes:
- https
consumes:
- application/json
produces:
- application/json
x-google-backend:
  address: https://cloudinary-ct-dev-run-4auv3abcfa-ew.a.run.app
paths:
  /CloudinaryNotification:
    post:
      summary: Cloudinary notification
      operationId: cloudinaryNotification
      responses:
        '200':
          description: A successful response
          schema:
            type: string